<a href="https://colab.research.google.com/github/profteachkids/CHE3023/blob/main/DimensionalAnalysisModelFitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default='plotly_dark'
from scipy.optimize import minimize

In [2]:
Re=np.random.uniform(2e3, 35e3, (100,))
Sc=np.random.uniform(0.6,2.5, (100,))
Sh=0.023* Re**0.83 * Sc**0.4
Sh = np.random.normal(loc=Sh, scale=0.1*Sh)

In [3]:
X=np.column_stack([np.ones_like(Re), np.log(Re), np.log(Sc)])
B=np.linalg.inv(X.T @ X) @ X.T @ np.log(Sh)
B

array([-3.80083084,  0.83043507,  0.42744373])

In [4]:
def sumsqerror(p):

    # return np.sum((Sh  - (p[0]* Re**p[1] * Sc**p[2]))**2) # non-linear regression
    return np.sum( (np.log(Sh) - (p[0] + p[1]*np.log(Re) + p[2]*np.log(Sc)))**2)  # transformed to linear

In [5]:
minimize(sumsqerror, [0.02, 0.75, 0.35])

      fun: 0.9907758538659637
 hess_inv: array([[ 0.86222885, -0.08909575, -0.0040521 ],
       [-0.08909575,  0.00931087, -0.00089556],
       [-0.0040521 , -0.00089556,  0.03418672]])
      jac: array([ 0.00000000e+00, -6.70552254e-08, -1.49011612e-08])
  message: 'Optimization terminated successfully.'
     nfev: 40
      nit: 5
     njev: 8
   status: 0
  success: True
        x: array([-3.8008198 ,  0.83043391,  0.42744384])

In [41]:
fig = make_subplots()
fig.add_trace(go.Scatter3d(x=Re, y=Sc, z=Sh, mode='markers', marker_size=3, marker_color=Sh))
ScGrid, ReGrid = np.meshgrid(np.linspace(0.6,2.5,20), np.linspace(2e3,35e3,20))
ShGrid = np.exp(B[0])*ReGrid**B[1] * ScGrid**B[2]
for iSc, iRe, iSh in zip(ScGrid, ReGrid, ShGrid):
    fig.add_trace(go.Scatter3d(x=iRe, y=iSc, z=iSh, mode='lines', line_color='gray'))

ReGrid, ScGrid = np.meshgrid(np.linspace(2e3,35e3,20), np.linspace(0.6,2.5,20), )
ShGrid = np.exp(B[0])*ReGrid**B[1] * ScGrid**B[2]
for iSc, iRe, iSh in zip(ScGrid, ReGrid, ShGrid):
    fig.add_trace(go.Scatter3d(x=iRe, y=iSc, z=iSh, mode='lines', line_color='gray'))


fig.update_layout(width=800, height=800, scene=dict(xaxis_title='Re', yaxis_title='Sc', zaxis_title='Sh'),
                  showlegend=False)

In [33]:
ShGrid

array([[  3.15966765,   3.68627893,   4.2128902 ,   4.73950148,
          5.26611275,   5.79272403,   6.31933531,   6.84594658,
          7.37255786,   7.89916913,   8.42578041,   8.95239168,
          9.47900296,  10.00561423,  10.53222551,  11.05883678,
         11.58544806,  12.11205934,  12.63867061,  13.16528189],
       [  5.30986596,   6.19484362,   7.07982128,   7.96479894,
          8.8497766 ,   9.73475426,  10.61973192,  11.50470958,
         12.38968724,  13.2746649 ,  14.15964256,  15.04462022,
         15.92959788,  16.81457554,  17.6995532 ,  18.58453085,
         19.46950851,  20.35448617,  21.23946383,  22.12444149],
       [  7.29035914,   8.505419  ,   9.72047886,  10.93553871,
         12.15059857,  13.36565843,  14.58071828,  15.79577814,
         17.010838  ,  18.22589786,  19.44095771,  20.65601757,
         21.87107743,  23.08613728,  24.30119714,  25.516257  ,
         26.73131685,  27.94637671,  29.16143657,  30.37649643],
       [  9.16518835,  10.69271974,  

In [ ]:
ReGrid

In [23]:
x=np.linspace(0,3,4)
y=np.linspace(5,8, 4)

In [24]:
for i,j in zip(x,y):
    print(i,j)

0.0 5.0
1.0 6.0
2.0 7.0
3.0 8.0


In [25]:
xx,yy = np.meshgrid(x,y)

In [26]:
for ix, iy in zip(xx,yy):
    print(ix,iy)

[0. 1. 2. 3.] [5. 5. 5. 5.]
[0. 1. 2. 3.] [6. 6. 6. 6.]
[0. 1. 2. 3.] [7. 7. 7. 7.]
[0. 1. 2. 3.] [8. 8. 8. 8.]


In [27]:
xx

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [28]:
yy

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.]])

In [21]:
xx

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [22]:
yy

array([[5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.]])

In [ ]:
x=np.lin