<a href="https://colab.research.google.com/github/profteachkids/CHE3023/blob/main/NRTL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import jax.numpy as jnp
import jax
R=8.314

In [26]:
# For the 3 component mixture: (1) Methanol, (2) Ethanol, and (3) Water system, 
# the matrices A, C, D are zeros, while B and alpha have been determined experimentally.
B=jnp.array( [[   0.,   -155.5,   -24.49],
 [ 190.06,    0.,    -55.17],
 [ 307.17,  670.44,    0.  ]])

alpha = jnp.array( [[0.,    0.305, 0.3  ],
 [0.305, 0.,    0.303],
 [0.3,   0.303, 0.   ]])

In [27]:
x12 = jnp.array([0.2,0.3])

In [28]:
def Gex(x,T):
  tau = B/T
  G = jnp.exp(-alpha * tau)
  return jnp.dot(x, jnp.matmul(x,tau*G)/jnp.matmul(x,G))

In [29]:
jnp.exp(jax.grad(Gex,0)(jnp.array([0.2,0.3,0.5]),300))

DeviceArray([1.0061771, 1.335594 , 1.4216974], dtype=float32)

In [38]:
def lngamma(x12,T):
    x = jnp.append(x12,1- x12.sum())
    tau = B/T
    G = jnp.exp(-alpha * tau)
    xG=jnp.matmul(x,G)
    xtauGdivxG = jnp.matmul(x,tau * G) / xG
    print(tau, xtauGdivxG)
    lngamma = xtauGdivxG+jnp.matmul(G * (tau - xtauGdivxG), x/xG)
    return lngamma

In [37]:
tau

NameError: ignored

In [39]:
lngamma(x12,300)

[[ 0.         -0.5183333  -0.08163333]
 [ 0.6335333   0.         -0.1839    ]
 [ 1.0239      2.2348      0.        ]] [ 0.6542138   0.5661521  -0.07343629]


DeviceArray([0.00615811, 0.2893762 , 0.3518515 ], dtype=float32)

In [32]:

tfm = jnp.eye(2) + jnp.broadcast_to(x12,(2,2))*jax.jacobian(lngamma,0)(x12,300)[:2,:]

In [33]:
tfm

DeviceArray([[ 1.0089608 , -0.19754106],
             [-0.22314115,  0.5773254 ]], dtype=float32)

In [34]:
dxdz = jnp.array([0.3,0.4])
d = jnp.matmul(tfm,dxdz)
d

DeviceArray([0.22367185, 0.16398782], dtype=float32)